services:
  mariadb:
    container_name: ok-facture_mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: aperture
      MARIADB_DATABASE: okfacture
    volumes:
      - ./.docker/mariadb/mysql:/var/lib/mysql